FROM ubuntu:14.04

RUN apt-get update && apt-get -y install python-software-properties software-properties-common && add-apt-repository -y ppa:fkrull/deadsnakes
RUN apt-get update && apt-get install -y python3-dev python3-pip build-essential python-dev python-pip python-tox python2.6 python2.6-dev python3.3 python3.3-dev git
